//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contato
    {
        public int contatosId { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string operadora { get; set; }
        public string genero { get; set; }
        public Nullable<int> fk_profissoes { get; set; }
    
        public virtual Profissoes Profissoes { get; set; }
    }
}
