//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CRUD_MVC5.Models
{
   
    
    public partial class Contato
    {
        public int contatosId { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string operadora { get; set; }
    }
}
