//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CRUD_MVC5.Models
{
  
    
    public partial class Funcionario
    {
        public int funcionarioId { get; set; }
        public string funcionarioNome { get; set; }
        public string funcionarioCPF { get; set; }
        public string funcionarioLogin { get; set; }
        public string funcionarioSenha { get; set; }
    }
}
