//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class ListaTelefonicaEntities : DbContext
    {
        public ListaTelefonicaEntities()
            : base("name=ListaTelefonicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contato> Contatos { get; set; }
        public DbSet<Funcionario> Funcionarios { get; set; }
        public DbSet<Profissoes> Profissoes1 { get; set; }
    }

  
}
