//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profisso
    {
        public Profisso()
        {
            this.Contatos = new HashSet<Contato>();
        }
    
        public int profissaoId { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Contato> Contatos { get; set; }
    }
}
